name = "do-kv-file"
main = "src/worker.js"
compatibility_date = "2025-03-01"

kv_namespaces = [
  { binding = "FILE_KV", id = "e3500720dd7c481dbc7fc808ade91eb6" }
]

durable_objects.bindings = [
  { name = "FILE_SESSION", class_name = "FileSession" }
]

[[migrations]]
tag = "v1"
# 将原来的 new_classes 改为 new_sqlite_classes
new_sqlite_classes = ["FileSession"]